# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 16dfb197c8321b3ee32c476ba48003df51fff0a7d6fc28c07692e8a74d61df8abbce838167bceb40d42b3a5a5a89e9bb1193caae11b70d9fa6d0fc2d1dd7ce0b

test:
  secret_key_base: 3228d61143857ad8b9da04e40cdd0da560731478edb57cdbc98d2b4cf4b6af738b0e3093954b891cc02fecb25a4566503779ca4ee94d980e3f77e610224af3ce

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
